# Generated by Django 3.1.1 on 2020-09-18 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='City')),
                ('area', models.ManyToManyField(to='units.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Country')),
                ('city', models.ManyToManyField(to='units.City')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Unit Title')),
                ('description', models.TextField(max_length=500, verbose_name='Unit Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='units_images/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('owner_email', models.EmailField(default='', max_length=254)),
                ('type', models.CharField(choices=[('CHALEH', 'CHALEH'), ('ROOM', 'ROOM'), ('FLAT', 'FLAT'), ('STUDIO', 'STUDIO')], default='ROOM', max_length=20)),
                ('amenities', models.ManyToManyField(to='units.Amenity')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.country')),
            ],
        ),
    ]
