# Generated by Django 3.1.1 on 2020-09-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_unit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='area',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
    ]
