# Generated by Django 3.1.1 on 2020-09-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20200918_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='num_bedrooms',
            field=models.IntegerField(default=2, verbose_name='Number of Bed rooms'),
            preserve_default=False,
        ),
    ]
