# Generated by Django 3.1.1 on 2020-10-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20200918_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('-active',), 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner_email',
            field=models.EmailField(default='fahdkuwait@gmail.com', max_length=254),
        ),
    ]
