# Generated by Django 3.1.1 on 2020-10-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
    ]
